# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-tools-dev
            - libxml2-utils
            - g++-multilib

matrix:
    include:
      - compiler: gcc
        env: BJAM_TOOLSET=gcc
      - compiler: gcc
        env: BJAM_TOOLSET=gcc-std11
      #- compiler: gcc
      #  env: BJAM_TOOLSET=gcc-m32
      - compiler: gcc
        env: BJAM_TOOLSET=gcc-std11m32
      #- compiler: clang
      #  env: BJAM_TOOLSET=clang
      - compiler: clang
        env: BJAM_TOOLSET=clang-std11
      - compiler: clang
        env: BJAM_TOOLSET=clang-m32
      #- compiler: clang
      #  env: BJAM_TOOLSET=clang-std11m32
      - compiler: gcc
        env: BJAM_TOOLSET=gcc-interopable
      - compiler: clang
        env: BJAM_TOOLSET=clang-interopable

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - touch Jamroot.jam
    - cd $HOME
    - |
        echo "using gcc : : g++-4.8 -Werror --std=c++03 -fsanitize=address ;" > ~/user-config.jam
        echo "using gcc : std11 : g++-4.8 -Werror --std=c++11 -fsanitize=address ;" >> ~/user-config.jam
        echo "using gcc : m32 : g++-4.8 -m32 -Werror -fsanitize=address ;" >> ~/user-config.jam
        echo "using gcc : std11m32 : g++-4.8 -m32 -Werror --std=c++11 -fsanitize=address ;" >> ~/user-config.jam
        echo "using clang : : clang++ -Werror --std=c++03 -fsanitize=address ;" >> ~/user-config.jam
        echo "using clang : std11 : clang++ -Werror --std=c++11 -fsanitize=address ;" >> ~/user-config.jam
        # sanitized=address not available for 32-bit clang on travis.
        echo "using clang : m32 : clang++ -m32 -Werror --std=c++03 ;" >> ~/user-config.jam
        echo "using clang : std11m32 : clang++ -m32 -Werror --std=c++11 ;" >> ~/user-config.jam
        echo "using gcc : interopable : g++-4.8 -Werror --std=c++03 -fsanitize=address -DBOOST_UNORDERED_INTEROPERABLE_NODES=1 ;" >> ~/user-config.jam
        echo "using clang : interopable : clang++ -Werror --std=c++11 -fsanitize=address -DBOOST_UNORDERED_INTEROPERABLE_NODES=1 ;" >> ~/user-config.jam
    - cat ~/user-config.jam
    - wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2
    - tar -xjf boost.tar.bz2
    - mv boost_1_63_0 boost
    - rm -r boost/boost/unordered

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam ${BJAM_TOOLSET} include=${HOME}/boost include=${TRAVIS_BUILD_DIR}/include
    - xmllint --noout ${TRAVIS_BUILD_DIR}/doc/ref.xml
